apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
      - name: project-container
        image: your-docker-registry/project-image:latest
        ports:
        - containerPort: 3000

